### ISSUE TITLE
Ranges for rate constants

### ISSUE THREAD

**Issue by jamesscottbrown** [max1s/CRNSynthesis#4]
There currently doesn't seem to be any way to tell a CRNSketch the upper and lower limits for each each rate constant.

You could add a new class:
```

class RateConstant:
    def __init__(self, name, min, max):
       self.name = name
       self.min = min
       self.max = max

    def __repr__(self):
         return "Rate constant %s <= %s <= %s"  % (self.min, self.name, self.max)

    def __str__(self):
         return "Rate constant %s <= %s <= %s"  % (self.min, self.name, self.max) 
```

And then add an extra argument to the ``__init__`` method of ``CRNSketch`` to receive a list of ``RateConstant`` objects.

**Comment by max1s** [comment]
Added!

Max
On 12 Dec 2017, at 14:42, James Scott-Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


There currently doesn't seem to be any way to tell a CRNSketch the upper and lower limits for each each rate constant.

You could add a new class:

And then add an extra argument to the __init__ method of CRNSketch to receive a list of RateConstant objects.
