### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by jamesscottbrown** [max1s/CRNSynthesis#5]
There is currently no way to pass-though 'other' constraints from the web-form.

**Comment by max1s** [comment]
Yes I was wondering how you want to proceed with this?

As in it we can have a generic string that inserts the constraints into the INIT part of the SMT-solver file?

Best wishes,

Max
On 12 Dec 2017, at 19:29, James Scott-Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


There is currently no way to pass-though 'other' constraints from the web-form.
